name: Deploy Serverless Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️ Set up Node.js (for Lambda packaging if needed)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️ Package Lambda functions
      - name: Package Lambdas
        run: |
          cd backend_lambda/signup
          zip -r signup.zip index.js node_modules || true

          cd ../login
          zip -r login.zip index.js node_modules || true

          cd ../events
          zip -r events.zip index.js || true

      # 4️ Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 5 Build Lambda packages
      - name: Build Lambda packages
        run: |
          cd backend_lambda/signup
          npm install
          zip -r signup.zip index.js node_modules package.json

          cd ../login
          npm install
          zip -r login.zip index.js node_modules package.json

          cd ../events
          npm install
          zip -r events.zip index.js node_modules package.json

          cd ../create_event
          npm install
          zip -r create-event.zip index.js node_modules package.json

          cd ../../

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 6 Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # 7 Terraform Plan
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan
        

      # 8 Terraform Apply 
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: terraform
        run: terraform apply -auto-approve

      
      - name: Build React frontend
        run: |
          cd frontend/frontend
          npm install
          npm run build
          cd ../../

      - name: Upload frontend to S3
        run: |
          aws s3 sync frontend/frontend/build s3://ticket-booking-serverless-frontend --delete

      - name: Invalidate CloudFront cache
        run: |
          DISTRIBUTION_ID=$(aws cloudfront list-distributions \
            --query "DistributionList.Items[?Origins.Items[0].DomainName=='ticket-booking-serverless-frontend.s3.amazonaws.com'].Id" \
            --output text)

          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"

        
